/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/attempts": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.attempts.id"];
          created_at?: parameters["rowFilter.attempts.created_at"];
          updated_at?: parameters["rowFilter.attempts.updated_at"];
          seconds?: parameters["rowFilter.attempts.seconds"];
          missed?: parameters["rowFilter.attempts.missed"];
          words?: parameters["rowFilter.attempts.words"];
          session_id?: parameters["rowFilter.attempts.session_id"];
          user_id?: parameters["rowFilter.attempts.user_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["attempts"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** attempts */
          attempts?: definitions["attempts"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.attempts.id"];
          created_at?: parameters["rowFilter.attempts.created_at"];
          updated_at?: parameters["rowFilter.attempts.updated_at"];
          seconds?: parameters["rowFilter.attempts.seconds"];
          missed?: parameters["rowFilter.attempts.missed"];
          words?: parameters["rowFilter.attempts.words"];
          session_id?: parameters["rowFilter.attempts.session_id"];
          user_id?: parameters["rowFilter.attempts.user_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.attempts.id"];
          created_at?: parameters["rowFilter.attempts.created_at"];
          updated_at?: parameters["rowFilter.attempts.updated_at"];
          seconds?: parameters["rowFilter.attempts.seconds"];
          missed?: parameters["rowFilter.attempts.missed"];
          words?: parameters["rowFilter.attempts.words"];
          session_id?: parameters["rowFilter.attempts.session_id"];
          user_id?: parameters["rowFilter.attempts.user_id"];
        };
        body: {
          /** attempts */
          attempts?: definitions["attempts"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/profiles": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          name?: parameters["rowFilter.profiles.name"];
          avatar?: parameters["rowFilter.profiles.avatar"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["profiles"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** profiles */
          profiles?: definitions["profiles"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          name?: parameters["rowFilter.profiles.name"];
          avatar?: parameters["rowFilter.profiles.avatar"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles.id"];
          name?: parameters["rowFilter.profiles.name"];
          avatar?: parameters["rowFilter.profiles.avatar"];
        };
        body: {
          /** profiles */
          profiles?: definitions["profiles"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/profiles_private": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles_private.id"];
          email?: parameters["rowFilter.profiles_private.email"];
          admin?: parameters["rowFilter.profiles_private.admin"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["profiles_private"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** profiles_private */
          profiles_private?: definitions["profiles_private"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles_private.id"];
          email?: parameters["rowFilter.profiles_private.email"];
          admin?: parameters["rowFilter.profiles_private.admin"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.profiles_private.id"];
          email?: parameters["rowFilter.profiles_private.email"];
          admin?: parameters["rowFilter.profiles_private.admin"];
        };
        body: {
          /** profiles_private */
          profiles_private?: definitions["profiles_private"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/sessions": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.sessions.id"];
          created_at?: parameters["rowFilter.sessions.created_at"];
          updated_at?: parameters["rowFilter.sessions.updated_at"];
          user_id?: parameters["rowFilter.sessions.user_id"];
          lines?: parameters["rowFilter.sessions.lines"];
          title?: parameters["rowFilter.sessions.title"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["sessions"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** sessions */
          sessions?: definitions["sessions"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.sessions.id"];
          created_at?: parameters["rowFilter.sessions.created_at"];
          updated_at?: parameters["rowFilter.sessions.updated_at"];
          user_id?: parameters["rowFilter.sessions.user_id"];
          lines?: parameters["rowFilter.sessions.lines"];
          title?: parameters["rowFilter.sessions.title"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.sessions.id"];
          created_at?: parameters["rowFilter.sessions.created_at"];
          updated_at?: parameters["rowFilter.sessions.updated_at"];
          user_id?: parameters["rowFilter.sessions.user_id"];
          lines?: parameters["rowFilter.sessions.lines"];
          title?: parameters["rowFilter.sessions.title"];
        };
        body: {
          /** sessions */
          sessions?: definitions["sessions"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/rpc/handle_new_user": {
    post: {
      parameters: {
        body: {
          args: { [key: string]: unknown };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
}

export interface definitions {
  attempts: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    created_at: string;
    updated_at: string;
    seconds: number;
    missed: number;
    words: number;
    /**
     * Note:
     * This is a Foreign Key to `sessions.id`.<fk table='sessions' column='id'/>
     */
    session_id: string;
    /**
     * Note:
     * This is a Foreign Key to `profiles.id`.<fk table='profiles' column='id'/>
     */
    user_id: string;
  };
  profiles: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    name?: string;
    avatar?: string;
  };
  profiles_private: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     * This is a Foreign Key to `profiles.id`.<fk table='profiles' column='id'/>
     */
    id: string;
    email?: string;
    admin: boolean;
  };
  sessions: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    created_at: string;
    updated_at: string;
    /**
     * Note:
     * This is a Foreign Key to `profiles.id`.<fk table='profiles' column='id'/>
     */
    user_id: string;
    lines: string;
    title: string;
  };
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object";
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** Preference */
  preferCount: "count=none";
  /** Filtering Columns */
  select: string;
  /** On Conflict */
  on_conflict: string;
  /** Ordering */
  order: string;
  /** Limiting and Pagination */
  range: string;
  /** Limiting and Pagination */
  rangeUnit: string;
  /** Limiting and Pagination */
  offset: string;
  /** Limiting and Pagination */
  limit: string;
  /** attempts */
  "body.attempts": definitions["attempts"];
  "rowFilter.attempts.id": string;
  "rowFilter.attempts.created_at": string;
  "rowFilter.attempts.updated_at": string;
  "rowFilter.attempts.seconds": string;
  "rowFilter.attempts.missed": string;
  "rowFilter.attempts.words": string;
  "rowFilter.attempts.session_id": string;
  "rowFilter.attempts.user_id": string;
  /** profiles */
  "body.profiles": definitions["profiles"];
  "rowFilter.profiles.id": string;
  "rowFilter.profiles.name": string;
  "rowFilter.profiles.avatar": string;
  /** profiles_private */
  "body.profiles_private": definitions["profiles_private"];
  "rowFilter.profiles_private.id": string;
  "rowFilter.profiles_private.email": string;
  "rowFilter.profiles_private.admin": string;
  /** sessions */
  "body.sessions": definitions["sessions"];
  "rowFilter.sessions.id": string;
  "rowFilter.sessions.created_at": string;
  "rowFilter.sessions.updated_at": string;
  "rowFilter.sessions.user_id": string;
  "rowFilter.sessions.lines": string;
  "rowFilter.sessions.title": string;
}

export interface operations {}

export interface external {}
